# Generated by Django 4.2.1 on 2024-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Contact',
            field=models.IntegerField(default=''),
        ),
    ]
